### ISSUE TITLE
Request: rerun tests on failure

### ISSUE THREAD

**Issue by ktchernov** [bitrise-steplib/steps-virtual-device-testing-for-ios#10]
Automation tests can be very flaky for various reasons. It would be great to have an option to rerun the tests (or just failing tests?) on test failure.

This feature exists in the Xcode Test step already: https://github.com/bitrise-steplib/steps-xcode-test/blob/master/step.yml

**Comment by bitce** [comment]
Hi @ktchernov!

Thanks for the suggestion, could you create a [feature request about this here on Discuss](https://discuss.bitrise.io/c/feature-request)? That's where we collect them and users can vote for requests so we can prioritise those that are most in need :)
