### ISSUE TITLE
failure(NotInstalled) 

### ISSUE THREAD

**Issue by kabirkhaan** [bitrise-steplib/steps-virtual-device-testing-for-ios#22]
Unable to install on virtual device failed. I am following the same build process as mentioned but my build is failing on install. Can you please help me on this issue. Thanks in advance

+------------------------------------------------------------------------------+

| (1) virtual-device-testing-for-ios@0                                         |
+------------------------------------------------------------------------------+
| id: virtual-device-testing-for-ios                                           |
| version: 0.9.11                                                              |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: go                                                                  |
| time: 2020-06-01T17:42:59Z                                                   |
+------------------------------------------------------------------------------+
|                                                                              |
Configs:
- ZipPath: /Users/vagrant/deploy/testbundle.zip
- TestTimeout: 900
- TestDevices:
---
Model     OS version   Orientation   Locale   
iphone7   12.3         portrait      en       
---
Upload IPAs
=> .xctestrun uploaded
Start test
=> Test started
Waiting for test results
- Validating
- (1/1) running
- (0/1) running
=> Test finished
Test results:
Model     OS version   Orientation   Locale   Outcome                            
iphone7   12.3         portrait      en       **failure(NotInstalled)**   
|                                                                              |
+---+---------------------------------------------------------------+----------+
| x | virtual-device-testing-for-ios@0 (exit code: 1)               | 3.9 min  |
+---+---------------------------------------------------------------+----------+
| Issue tracker: ...itrise-steplib/steps-virtual-device-testing-for-ios/issues |
| Source: ...//github.com/bitrise-steplib/steps-virtual-device-testing-for-ios |
+---+---------------------------------------------------------------+----------+

**Comment by non-binary** [comment]
Hi @kabirkhaan,

Please open a ticket on https://www.bitrise.io/bitrise-support and we will assist you over email. This method of contacting Bitrise is primarily for reporting bugs in the step.
